<a href="https://colab.research.google.com/github/kajall120/Data_science_Lab_SE_64/blob/main/with_function3x3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a 3x3 square matrix
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Original 3x3 Matrix:")
print(matrix)

# Compute the determinant of the matrix
determinant = np.linalg.det(matrix)

print("\nDeterminant of the matrix:")
print(determinant)

Original 3x3 Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of the matrix:
0.0
