<a href="https://colab.research.google.com/github/kajall120/Data_science_Lab_SE_64/blob/main/withfunction_inverse.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

First, we'll import the `numpy` library, define a sample matrix, and then use `numpy.linalg.inv()` to calculate its inverse.

In [5]:
import numpy as np

# Define an invertible 3x3 matrix
C = np.array([[1, 2, 0],
              [0, 1, 0],
              [1, 0, 1]])

print("Original Matrix C:")
print(C)

# Calculate the determinant to ensure it's non-singular
det_C = np.linalg.det(C)
print(f"\nDeterminant of Matrix C: {det_C:.4f}")

# Calculate the inverse of the matrix
try:
    inverse_C = np.linalg.inv(C)
    print("\nInverse of Matrix C:")
    print(inverse_C)

    # Verify by multiplying the original matrix by its inverse
    identity_check = np.dot(C, inverse_C)
    print("\nProduct of C and its inverse (should be an identity matrix):")
    print(identity_check)
except np.linalg.LinAlgError as e:
    print(f"\nError: {e}")
    print("This matrix is singular and does not have an inverse.")

Original Matrix C:
[[1 2 0]
 [0 1 0]
 [1 0 1]]

Determinant of Matrix C: 1.0000

Inverse of Matrix C:
[[ 1. -2.  0.]
 [-0.  1. -0.]
 [-1.  2.  1.]]

Product of C and its inverse (should be an identity matrix):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
